### PR TITLE
Adds analytics_jenkins playbook

### PR DESCRIPTION
**Pull request by pomegranited**
Cherry-picks commits from edx/configuration to add the analytics_jenkins playbook and related role changes.

Also includes the `jenkins_nginx_port` variable change as required by edx-analytics-configuration/jenkins, and fixes Jenkins proxied content url rewrites.

**JIRA tickets**: [OC-1561](https://tasks.opencraft.com/browse/OC-1561)

**Screenshots**:
screen shot 2016-05-06 at 6 07 21 pm

**Production URL**: See [secure epodx PR #1](https://github.com/hks-epod/epodx/pull/1)

**Testing instructions**:
1. Verify that the Jenkins setup on epodx analytics instance is as desired.

**Author notes and concerns**:
1. Need to remove the jenkins user password, since it uses ssh tunnels instead.
2. Finish documentation changes for analytics setup.

**Reviewers**
- [x] @jbzdak

### CODE REVIEW

**Comment by e-kolpakov** [comment]
@pomegranited was it cherry-picked from upstream? If that's the case, I believe we don't need to code-review and verify it again.

**Comment by pomegranited** [comment]
@e-kolpakov The first 8 commits are cherry-picked from upstream, and have been reviewed.
The last 3 are cherry-picked from new PRs, which can be reviewed separately.
- [PR #3025](https://github.com/edx/configuration/pull/3025) - Adds `jenkins_protocol`
- [PR #3026](https://github.com/edx/configuration/pull/3026) - Uses `proxy_set_header Host $http_host`
- [PR #3026](https://github.com/edx/configuration/pull/3027) - Allows `JENKINS_ANALYTICS_AUTH_REALM: none`

**Comment by jbzdak** [comment]
:+1:

**Comment by pomegranited** [comment]
@bradenmacdonald  I don't have permissions to push to hks-epod/configuration.  Can you merge this PR, or give me permission to do it?  (I didn't squash the commits this time, because they're all cherry-picked.)

**Comment by bradenmacdonald** [comment]
@pomegranited Added you.

**Pull request merged**
